### ISSUE TITLE
a noob question

### ISSUE THREAD

**Issue by meteus** [ThaisenPM/Cheat-Loader-CSGO-2.0#1]
First of, this is a great project, thank you for sharing with us. I will use it for non commerce use but i will ask a question, can we add junk code in these .cs files sir?

**Comment by xbRead** [comment]
the .cs files are web based and shouldn't need junk code?

**Comment by skmuzz** [comment]
The only thing you should maybe be concerned about with Valve Anti Cheat is the Injector (Referenced Below)
https://github.com/ThaisenPM/Cheat-Loader-CSGO-2.0/tree/master/MetroLoader/MetroLoader/Injection

If it makes you feel better about being banned through heuristic detection you can add some junk code to try to change the signature. A quick google returned [This](https://github.com/The-FBI/JunkGenerator) project. Good luck.

**Comment by ThaisenPM** [comment]
@skmuzz answered. Thank you
