### ISSUE TITLE
not working injecting

### ISSUE THREAD

**Issue by Heyter** [ThaisenPM/Cheat-Loader-CSGO-2.0#10]
i did everything right, it says "Successfully Injected"
hmodule return 0x000000

if injected with extreme injector then all okay.

**Comment by ThaisenPM** [comment]
Make sure CS:GO is open, make sure your web host is sending all of the data for your dll

**Comment by Heyter** [comment]
Fixed: need compile project with 32bit.
If game = 32bit then and project must be 32bit xD
