### ISSUE TITLE
Pay you to set it up for me?

### ISSUE THREAD

**Issue by moxskull** [ThaisenPM/Cheat-Loader-CSGO-2.0#11]
I would pay you if you could set up the whole Cheatloader 2 project,
I tried it by myself edited the config and so on. everything that was in your description, But it wont work.
10€ Paysafecard? or Steam money? even possible?

Sry to pull an issue but im new to github

**Comment by ThaisenPM** [comment]
No. If you connect to my Discord you would see that offering any money for setting up this loader is not allowed. If you wish to purchase a custom loader from me head to https://selly.gg/@Thaisen. Otherwise keep trying.

**Comment by moxskull** [comment]
Thank you very much for your answer. Im sorry but currently i cant afford a loader for 50$
