### ISSUE TITLE
what web host will work?

### ISSUE THREAD

**Issue by fiveseven57memer** [ThaisenPM/Cheat-Loader-CSGO-2.0#12]
is there any free web hosting that will work with this loader? byet and 000 don't work, according to this - https://github.com/ThaisenPM/Cheat-Loader-CSGO-2.0/issues/7, they don't allow the data to transfer. so, any help?

**Comment by moxskull** [comment]
No, there are probably some hosts but with the data transfer (if youre cheat community grows, the more) use nitrado.de (a few cents to 2€)
