### ISSUE TITLE
Pw incorrect/ xenforo

### ISSUE THREAD

**Issue by moxskull** [ThaisenPM/Cheat-Loader-CSGO-2.0#13]
Hey im here again...
do you know what i have to put in for the numbers (0,1,2) in this line of code if im using xenforo or were i could find it / where it would be safed under mybb?

rivate void webBrowser1_DocumentCompleted(object sender, WebBrowserDocumentCompletedEventArgs e)
        {
            if (username == true)
            {
                if (webBrowser1.DocumentText.Contains("0"))
                {
                    username = false;
                    MessageBox.Show("Password incorrect");
                }
                else if (webBrowser1.DocumentText.Contains("1"))
                {
                    usergroup = true;
                    username = false;
                    webBrowser2.Navigate("http://www.1tapcheats.com/group.php?username=" + metroTextBox1.Text);
                }
                else if (webBrowser2.DocumentText.Contains("2"))
                {
                    username = false;
                    MessageBox.Show("No user with that name");
                }

Thank you for answear!

**Comment by ThaisenPM** [comment]
For Xenforo you need to make calls through an API, database reading like this will not work
