### ISSUE TITLE
What Api or how to implement?

### ISSUE THREAD

**Issue by moxskull** [ThaisenPM/Cheat-Loader-CSGO-2.0#14]
I have 0 knowledge about such stuff is there some api for database reading and i have to implement it to your code or what?

**Comment by moxskull** [comment]
I found something here: https://brcheats.net/forum/index.php?threads/interação-com-xenforo-sistema-de-login-com-xenforo.1002/ 
is that something in kind of you mean ?

**Comment by ThaisenPM** [comment]
Do some research into RestFUL API's
