### ISSUE TITLE
Error: Properties does not exist in the current context

### ISSUE THREAD

**Issue by Alex2000u** [ThaisenPM/Cheat-Loader-CSGO-2.0#15]
For Example I get this error in Form1.cs in line 44

**Comment by moxskull** [comment]
Me too

**Comment by ThaisenPM** [comment]
You guys managed to clear the System.Properties settings I had set. Just re-add them

**Comment by moxskull** [comment]
Cleared the system.Properties? I didnt even started to edit something (only the form?!) & how to readd them
