### ISSUE TITLE
Injector doesnt work?

### ISSUE THREAD

**Issue by moxskull** [ThaisenPM/Cheat-Loader-CSGO-2.0#18]
I did setup everything, to work:

Sign in works great & fast, the usergroup check works too but the injection seems to fail somehow..
It says it has injected succesfully but in CSGO, i cant open the cheat menu. I tried 3 different cheats (ayyware, some external bullshit, etc), but its never truly injected

(I never have done my own injector, can it be that the injector is outdated or so?)

Thanks buddy, im nearly finished!

**Comment by moxskull** [comment]
Yeah i saw the issue down below, try to fix the problem in the evening closing then the issue myself.

**Comment by ThaisenPM** [comment]
000webhost and some other free hosts do not send all of the dll data. Confirm the dll is the correct size. The injection library is not out of date, it's just not getting all of the dll data
