### ISSUE TITLE
Junkcode

### ISSUE THREAD

**Issue by Petrju** [ThaisenPM/Cheat-Loader-CSGO-2.0#21]
Junkcode is good to protect and made UD :1st_place_medal:

**Comment by moxskull** [comment]
Stop Spamming

**Comment by Petrju** [comment]
sorry :( miss click dude

**Comment by Petrju** [comment]
@moxskull junkcode and made ud this loader ?

**Comment by moxskull** [comment]
I don’t understand what you want: adding junkcode to the injector makes it ud

**Comment by moxskull** [comment]
Isnt meant aggressive (sounds so lol)😂

**Comment by ThaisenPM** [comment]
Closed: Stupid question
