### ISSUE TITLE
Htaccess

### ISSUE THREAD

**Issue by moxskull** [ThaisenPM/Cheat-Loader-CSGO-2.0#23]
The „ needs to be .* ? Am i right there? Bruh never did a htaccess 😂😂

**Comment by TronexEngine** [comment]
the file name is .htaccess lol ;D

**Comment by moxskull** [comment]
@TronexEngine i know that but Thaisen said in the code is a small error?? I cant find an error 😑🤧😂

**Comment by moxskull** [comment]
nvm downloaded latest project files xD
