### ISSUE TITLE
Im aint using free host

### ISSUE THREAD

**Issue by moxskull** [ThaisenPM/Cheat-Loader-CSGO-2.0#25]
Im using Nitrado.de , would there another option to download the file (google cloud or so?)

**Comment by moxskull** [comment]
So the Host told me it is downloading everything. Im taking the other Issue of another user to ask: what bit do i have to use (build 64x or 84x?) my csgo process says csgo.exe*32 idk what to do now 😳

**Comment by astron-dev** [comment]
x86

**Comment by ThaisenPM** [comment]
All CS:GO Dlls are x86
