### ISSUE TITLE
Yea.. .htaccess [not total noob, maybe..]

### ISSUE THREAD

**Issue by SurprisedBH** [ThaisenPM/Cheat-Loader-CSGO-2.0#26]
Hi.   
(I have never played with .htaccess, and I am not experienced at c#. I prefer c++, so please be patient)
As I read here: [Issue on github](https://github.com/ThaisenPM/Cheat-Loader-CSGO-2.0/issues/22)
there is a problem with this code :

     SetEnvIfNoCase User-Agent "a" good_bot
    <FilesMatch ".dll">
        Order Deny,Allow
        Deny from All
        Allow from env=good_bot
    </FilesMatch>

Soo.. I did some research, and I found this: [link to stackoverwolf thread](https://stackoverflow.com/questions/9943042/htaccess-order-deny-allow-deny)

With this knowledge i tried to fix this "code":

     SetEnvIfNoCase User-Agent "a" good_bot
    <FilesMatch ".dll">
        Order Allow,Deny
        Allow from env=good_bot
    </FilesMatch>

And guess what? (You have probably guessed..  x D) Still dosent work..
.htaccess is working but this "CustomUserString" is not..
NO ONE CAN DOWNLOAD dlls, always getting 403 forbidden

Maybe there is something wrong with this c# "shit"?
`wb.Headers.Add("User-Agent", "a");`

Thanks for reading, hope You'll help me..
Have a nice day!

**Comment by moxskull** [comment]
In my turn it works fine

**Comment by moxskull** [comment]
You just have an Allow duplicated

**Comment by moxskull** [comment]
Watch for newest Project files! (Redownload by Github ) , links have to be fixed

**Comment by SurprisedBH** [comment]
> You just have an Allow duplicated
Could you send me your .htaccess?
It would be helpful ;D

**Comment by moxskull** [comment]
Its acctually the same as in the readme boiii

**Comment by moxskull** [comment]
Allow , deny (not more!) the userstring can be random shit (i prefer password gen) use only Letters & Numbers but like 164 letters & numbers

**Comment by SurprisedBH** [comment]
If this is true

    SetEnvIfNoCase User-Agent "CustomUseragentString" good_bot
    <FilesMatch ".dll">
    	Order Deny,Allow
    	Deny from All
    	Allow from env=good_bot
    </FilesMatch>

This is bull shit.. Is it? 
[overwolf](https://stackoverflow.com/questions/9943042/htaccess-order-deny-allow-deny)

**Comment by moxskull** [comment]
That post on overwolf is about blocking an ip and doesnt habe to do with it. Ignore them the useragent in the C# have to be the same as in htaccess. The code above is the correct one

**Comment by SurprisedBH** [comment]
Sorry, I did not read it exactly..
I will try it tomorrow..
Thank you!

**Comment by SurprisedBH** [comment]
Worked, I am braindead
