### ISSUE TITLE
Always incorrect password

### ISSUE THREAD

**Issue by Megaeloelo** [ThaisenPM/Cheat-Loader-CSGO-2.0#28]
I tried manually going to check.php url with username and password and it outputs 1 so credentials are working, but in loader there is always incorrect password. It may be because of asynch of webbrowser1 but I am struggling to fix it.
Any help?
BTW. For what are the usergroups?
Sorry for bad english.

**Comment by moxskull** [comment]
The User groups are the groups of the users.(gg) you did something wrong code at my turn works fine

**Comment by Megaeloelo** [comment]
I checked connectivity with the database using check.php?username=MYUSERNAME&password=MYPASSWORD and it outputs "1" when I type wrong it outputs "0" but in loader it's always incorrect password.

**Comment by Megaeloelo** [comment]
I will setup the source from fresh, cause maybe something is deleted or something like that.

**Comment by moxskull** [comment]
The login has nothing to do with your database in that case....change all yourdomain links to every link of yours & redirect to your mybb usergroup links, if you dont know what a usergroup is im sorry but you should then learn mybb standard knowledge. 😕

**Comment by Megaeloelo** [comment]
I have a phpbb so I needed change something in check.php because it was reading "password" row but in database it was "user_password"

**Comment by moxskull** [comment]
Take my tipp and use mybb the code isnt meant for phpbb

**Comment by Megaeloelo** [comment]
Still not working on mybb.

**Comment by moxskull** [comment]
Then you worked not very well on it

**Comment by moxskull** [comment]
as i said it works fine for me, updated the injector anything runs but injections isnt running but i fix that

**Comment by Megaeloelo** [comment]
I changed all of the links in form1, 3 and 4. I checked manually that my test user is working, it outputs 1.
The loader just can't see that. When I changed the if else statements to just if it works, but it displays that messagebox with "password incorrect", but it logs in. I think that the site isn't loading correctly in loader and that's why only first if statement is working (that one with wrong password).

**Comment by Megaeloelo** [comment]
It's like loader thinks that site outputs 0 AND 1.
O_o

**Comment by moxskull** [comment]
Dont change any if statements! Search your usergroup of mybb out and type it in the code ! (Google is your friend)

**Comment by Megaeloelo** [comment]
The usergroup is working fine, just loader can't go futher than first "if"

**Comment by moxskull** [comment]
Seems like you didnt even read anything about mybb.... if you login on your bb (as user) it redirects via link (like google.com) in that link is a 1 OR 0 (if you succesfully logged in / not) Buddy trust me, my code works fine you f*cked something up there. 😂 (redownload and start from scratch, would be better)

**Comment by Megaeloelo** [comment]
I done it 3 times...
BTW. I'm not as that dumb in programming.

**Comment by Megaeloelo** [comment]
Do I need to give you my links? So you can test it

**Comment by moxskull** [comment]
I didnt said you was dumb, but you didnt know what a usergroup is ?! Its simple english codinglanguages use that ... Yeah send me a link to your bb, and i look what i can do

**Comment by Megaeloelo** [comment]
http://razj.ugu.pl/Loader/check.php?username=
http://razj.ugu.pl/Loader/group.php?username=
http://razj.ugu.pl/Loader/hwid.php?username=

**Comment by moxskull** [comment]
Did you changed the config.ini file?

**Comment by Megaeloelo** [comment]
Yes all changed with correct names and password.

**Comment by moxskull** [comment]
I cant really see that something is wrong with the links cause the programm adds a few strings automatically. Wait until Thaisen sees that, im not allowed to help you with the code (c#) neither to set it up for you. Good luck buddy

**Comment by Megaeloelo** [comment]
So I will wait.
Anyway thx for help.

**Comment by DanielK1511** [comment]
Seems like he ain't gonna answer. Why don't you don't take a look at my bb? 1tapcheats.com

**Comment by Megaeloelo** [comment]
I just writed my own loader. It's actually easy.
