### ISSUE TITLE
dll not downloading

### ISSUE THREAD

**Issue by Inf3ct3d1337** [ThaisenPM/Cheat-Loader-CSGO-2.0#7]
So I've set the dll links right but when I start the launcher and try to inject it will create a cheat.dll in the temp directory but it's only 1kb, so I guess it's not downloading from my website, the launcher says injection successfully but nothing happens

Any fix? (:(

**Comment by ShiningDev** [comment]
I think this fork fixed that: https://github.com/bobbyobrien44/Cheat-Loader-CSGO-2.0

**Comment by Inf3ct3d1337** [comment]
Nope, not working :(

**Comment by machado-rev** [comment]
Are you opening as Administrator? Here works well

**Comment by ThaisenPM** [comment]
Your web host is not allowing the data to transfer. AKA don't use 000webhost

**Comment by Inf3ct3d1337** [comment]
Ah, haven't thought about this. That was the problem, although I'm not using 000webhost

Thanks
